version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: carla-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: carla
      MONGO_INITDB_ROOT_PASSWORD: carla123
